### ISSUE TITLE
How does referencing CSS files work?

### ISSUE THREAD

**Issue by madelson** [AzureADQuickStarts/B2C-AzureBlobStorage-Client#2]
Hello,

I noticed that your HTML files have localhost references for CSS files like:
```
 <link href="http://localhost/wingtip/css/global.css" rel="stylesheet" type="text/css" />
```

Does this work when deployed to BLOB storage?

**Comment by MINDoSOFT** [comment]
You need to replace localhost with the storage container url.

**Comment by derisen** [comment]
Closing as this repo is being archived.
